permalink: /:year/:month/:title

markdown: redcarpet

exclude: ["README.md", "Rakefile", "Gemfile"]
auto: false
highlighter: true
safe: false

title: "Kasper Munck"
author:
  name: "Kasper Munck"
  email: kasper@muncken.dk
  github: kaspermunck
  twitter: kaspermunck

assets:
  sources:
    - _assets/css

plugins:
  - jekyll-assets

production_url: http://kaspermunck.github.io

analytics:
  google_id: "UA-31685958-1"
