title: Kasper Munck
author:
  name: Kasper Munck
  bio: "bio TBD"
description: A personal blog

markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
