permalink: /:year/:month/:title

markdown: redcarpet

exclude: ["README.md", "Rakefile"]
auto: false
pygments: true
safe: false

title: "Kasper Munck"
author:
  name: "Kasper Munck"
  email: kasper@muncken.dk
  github: kaspermunck
  twitter: kaspermunck

production_url: http://kaspermunck.github.io

analytics:
  google_id: "UA-31685958-1"
