title: Kasper Munck
author:
  name: Kasper Munck
  bio: "Engineer(ing manager), forever learning and building with technology"
description: A personal blog

markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title/

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
